image: python:3.5

definitions:
  steps:
    - step: &run-tests
        caches:
          - pip
        script:
          - apt-get -y -qq update || true
          - apt-get -y -qq install mercurial
          - pip install .[ci]
          - tox -e py$((34+${BITBUCKET_PARALLEL_STEP}))
          - python setup.py bdist_wheel sdist
        artifacts:
          - dist/*
    - step: &deploy
        script:
          - apt-get -y -qq update || true
          - apt-get -y -qq install mercurial
          - pip install .[ci]
          - twine upload --repository-url "${PYPI_REPOSITORY}" -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}" --disable-progress-bar dist/*

pipelines:
  default:
    - parallel:
      - step:
          <<: *run-tests
          image: python:3.5
      - step:
          <<: *run-tests
          image: python:3.6
      - step:
          <<: *run-tests
          image: python:3.7
    - step:
        <<: *deploy
        name: Deploy to TestPyPI
        deployment: test
    - step:
        <<: *deploy
        name: Deploy to PyPI
        deployment: production
        trigger: manual
